### ISSUE TITLE
Issue with python/Tutorials files

### ISSUE THREAD

**Issue by clemc98** [thliebig/openEMS-Project#14]
Hi, 
I'm experiencing an issue with 2 example files in the subfolder python/Tutorials.
Bent_Patch_Antenna.py and CRLH_Extraction.py doesn't work.

For Bent_Patch_Antenna.py I have this issue :
```
Traceback (most recent call last):
  File "Bent_Patch_Antenna.py", line 81, in <module>
    CSX.AddBox(patch, priority=10, start=start, stop=stop, edges2grid='all') # add a box-primitive to the metal property 'patch'
AttributeError: 'CSXCAD.CSXCAD.ContinuousStructure' object has no attribute 'AddBox'

```

And for CRLH_Extraction.py I have this one :
```
Traceback (most recent call last):
  File "CRLH_Extraction.py", line 136, in <module>
    mesh_hint = CRLH.createCell()
  File "CRLH_Extraction.py", line 60, in createCell
    mesh = box.GetGridHint('x', metal_edge_res=self.edge_resolution, down_dir=False)
AttributeError: 'CSXCAD.CSPrimitives.CSPrimBox' object has no attribute 'GetGridHint'

```

**Comment by thliebig** [comment]
This issue should have been opened at the openEMS submodule, but I agree that the git layout is difficult to understand.
The first issue does not exist like this anymore. The second is still open. I'm not sure why... I will have a look
