### ISSUE TITLE
Invalid float in temp file

### ISSUE THREAD

**Issue by kyle-beatty** [thliebig/openEMS-Project#212]
I am running openEMS on Python 3.11.9. My OS is Windows 11 Enterprise. When I run the following code, adapted from this [tutorial](https://docs.openems.de/python/openEMS/Tutorials/Rect_Waveguide.html), I get the results shown below the code. The file containing the invalid float is `port_it_0`, and it is copied below the output. The program also does not write the xml file `rect_wg.xml`

### Code

```import datetime
import os, tempfile
from pylab import *

# Add dll folder to trusted locations
dll_directory = 'C:\\Users\\KyleBeatty\\Downloads\\openEMS_v0.0.36\\openEMS\\python'
os.add_dll_directory(dll_directory)

from CSXCAD import ContinuousStructure
from openEMS import openEMS
from openEMS.physical_constants import *

now = datetime.datetime.now()
now_string = now.strftime('%m-%d_%H-%M')
Sim_Path = os.path.join(os.getcwd(), 'Rect_WGi_{}'.format(now_string))


post_proc_only = False
unit = 1e-6

a = 10700
b = 4300
length = 50000

f_start = 20e9
f_0 = 24e9
f_stop = 26e9
lambda0 = C0/f_0/unit;

TE_mode = 'TE10'

mesh_res = lambda0 / 30

FDTD = openEMS(NrTS=1e4)
FDTD.SetGaussExcite(0.5 * (f_start+f_stop), 0.5 * (f_stop-f_start))

FDTD.SetBoundaryCond([0, 0, 0, 0, 3, 3])

# set up geometry and mesh

CSX = ContinuousStructure()
FDTD.SetCSX(CSX)
mesh = CSX.GetGrid()
mesh.SetDeltaUnit(unit)

mesh.AddLine('x', [0, a])
mesh.AddLine('y', [0, b])
mesh.AddLine('z', [0, length])

# apply the waveguide port

ports = []
start = [0, 0, 10*mesh_res]
stop = [a, b, 15 * mesh_res]

mesh.AddLine('z', [start[2], stop[2]])
ports.append(FDTD.AddRectWaveGuidePort(0, start, stop, 'z', a*unit, b*unit, TE_mode, 1))

start = [0, 0, length- 10*mesh_res]
stop = [a, b, length - 15 * mesh_res]

mesh.AddLine('z', [start[2], stop[2]])
ports.append(FDTD.AddRectWaveGuidePort(0, start, stop, 'z', a*unit, b*unit, TE_mode))

mesh.SmoothMeshLines('all', mesh_res, ratio=1.4)

# Define dump box
Et = CSX.AddDump('Et', file_type=0, sub_sampling=[2, 2, 2])
start = [0, 0, 0]
stop = [a, b, length]
Et.AddBox(start, stop)

# Run simulation
if True:  # debugging only
    CSX_file = os.path.join(Sim_Path, 'rect_wg.xml')
    if not os.path.exists(Sim_Path):
        os.mkdir(Sim_Path)
    print('writing to xml')
    CSX.Write2XML(CSX_file)
    print('written to xml')
    #from CSXCAD import AppCSXCAD_BIN
    #os.system(AppCSXCAD_BIN + ' "{}"'.format(CSX_file))

if not post_proc_only:
    FDTD.Run(Sim_Path, cleanup=True)

# post-processing and plotting
freq = linspace(f_start, f_stop, 201)
for port in ports:
    #print('{} {}'.format(Sim_Path, freq))
    port.CalcPort(Sim_Path, freq)
```

### Output

```
writing to xml
written to xml
 ----------------------------------------------------------------------
 | openEMS 64bit -- version v0.0.36
 | (C) 2010-2023 Thorsten Liebig <thorsten.liebig@gmx.de>  GPL license
 ----------------------------------------------------------------------
        Used external libraries:
                CSXCAD -- Version: v0.6.3
                hdf5   -- Version: 1.12.0
                          compiled against: HDF5 library version: 1.12.0
                tinyxml -- compiled against: 2.6.2
                fparser
                boost  -- compiled against: 1_72
                vtk -- Version: 8.2.0
                       compiled against: 8.2.0

Create FDTD operator (compressed SSE + multi-threading)
FDTD simulation size: 27x12x132 --> 42768 FDTD cells
FDTD timestep is: 5.18459e-13 s; Nyquist rate: 37 timesteps @2.60648e+10 Hz
Excitation signal length is: 1842 timesteps (9.55001e-10s)
Max. number of timesteps: 10000 ( --> 5.42888 * Excitation signal length)
Create FDTD engine (compressed SSE + multi-threading)
Running FDTD engine... this may take a while... grab a cup of coffee?!?
[@        4s] Timestep:         3546 || Speed:   37.9 MC/s (1.129e-03 s/TS) || Energy: ~2.14e-30 (-81.53dB)
Time for 3546 iterations with 42768.00 cells : 4.01 sec
Speed: 37.86 MCells/s
file: C:\Users\KyleBeatty\python\mwe\Rect_WGi_06-17_13-09\port_ut_0
file: C:\Users\KyleBeatty\python\mwe\Rect_WGi_06-17_13-09\port_it_0
Traceback (most recent call last):
  File "C:\Users\KyleBeatty\python\mwe\script.py", line 91, in <module>
    port.CalcPort(Sim_Path, freq)
  File "C:\Users\KyleBeatty\AppData\Local\Programs\Python\Python311\Lib\site-packages\openEMS\ports.py", line 379, in CalcPort
    super(WaveguidePort, self).CalcPort(sim_path, freq, ref_impedance, ref_plane_shift, signal_type)
  File "C:\Users\KyleBeatty\AppData\Local\Programs\Python\Python311\Lib\site-packages\openEMS\ports.py", line 105, in CalcPort
    self.ReadUIData(sim_path, freq, signal_type)
  File "C:\Users\KyleBeatty\AppData\Local\Programs\Python\Python311\Lib\site-packages\openEMS\ports.py", line 96, in ReadUIData
    self.i_data = UI_data(self.I_filenames, sim_path, freq, signal_type )
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KyleBeatty\AppData\Local\Programs\Python\Python311\Lib\site-packages\openEMS\ports.py", line 44, in __init__
    tmp = np.loadtxt(os.path.join(path, fn),comments='%')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KyleBeatty\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KyleBeatty\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\npyio.py", line 1016, in _read
    arr = _load_from_filelike(
          ^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string '-04.4.92535963379e-12' to float64 at row 0, column 3.
```

### port_it_0

```
% time-domain current mode matching by openEMS v0.0.36 @Mon Jun 17 13:09:10 2024
% start-coordinates: (0.000411538,0.000390909,0.0437543) m -> [1,1,111]
% stop-coordinates: (0.0102885,0.00390909,0.0437543) m -> [25,10,111]
% t/s	current	mode_purity
2.5922945441e-13	-0	-04.4.92535963379e-12	-0	-0
9.59148981317e-12	-0	-0
1.42576199926e-11	-0	-0
1.89237501719e-11	-0	-0
2.35898803513e-11	-0	-0
2.82560105307e-11	-0	-0
3.29221407101e-11	-0	-0
3.75882708895e-11	-0	-0
4.22544010688e-11	-0	-0
4.69205312482e-11	-0	-0
5.15866614276e-11	-0	-0
5.6252791607e-11	-0	-0
6.09189217864e-11	-0	-0
6.55850519657e-11	-0	-0
7.02511821451e-11	-0	-0
7.49173123245e-11	-0	-0
7.95834425039e-11	-0	-0
8.42495726833e-11	-0	-0
8.89157028626e-11	-9.78133874256e-35	-0.996632614438
9.3581833042e-11	-4.06149317204e-31	-0.996633920959
9.82479632214e-11	-6.94492110087e-28	-0.996633920774
1.02914093401e-10	-5.25238438687e-25	-0.996633922279
1.0758022358e-10	-1.84560944446e-22	-0.996633927562
1.1224635376e-10	-3.1072505977e-20	-0.9966339204
1.16912483939e-10	-2.53540224643e-18	-0.996633921914
1.21578614118e-10	-9.89358009134e-17	-0.996633924393
1.26244744298e-10	-1.74597994974e-15	-0.996633918863
1.30910874477e-10	-1.1785180562e-14	-0.996633922419
1.35577004656e-10	-1.07156186645e-14	-0.99663392561
1.40243134836e-10	8.29699031628e-14	-0.996633921011
1.44909265015e-10	4.31538573206e-14	-0.996633910141
1.49575395195e-10	-8.29425240999e-14	-0.996633912157
1.54241525374e-10	-1.21917971136e-13	-0.996633926314
1.58907655553e-10	-7.7342996372e-14	-0.996633916907
1.63573785733e-10	-1.26308532363e-14	-0.996633955125
1.68239915912e-10	1.5271536217e-13	-0.996633925794
1.72906046091e-10	2.40379805083e-13	-0.996633917287
1.77572176271e-10	2.09558083533e-13	-0.996633916899
1.8223830645e-10	3.35789393529e-14	-0.996634010794
1.8690443663e-10	-2.01066359515e-13	-0.996633931928
1.91570566809e-10	-4.26921822911e-13	-0.996633920558
1.96236696988e-10	-5.04811906028e-13	-0.996633921362
2.00902827168e-10	-3.12314169773e-13	-0.996633913376
2.05568957347e-10	1.30772375019e-13	-0.996633844227
2.10235087527e-10	6.72892556075e-13	-0.996633929968
2.14901217706e-10	1.04102258953e-12	-0.996633917071
2.19567347885e-10	9.66112444278e-13	-0.996633922856
2.24233478065e-10	3.30241509135e-13	-0.996633903903
2.28899608244e-10	-7.18628364766e-13	-0.99663390448
2.33565738423e-10	-1.74927871925e-12	-0.996633919679
2.38231868603e-10	-2.18742759067e-12	-0.996633926975
2.42897998782e-10	-1.58722630032e-12	-0.996633909565
2.47564128962e-10	7.78420550591e-14	-0.996634059614
2.52230259141e-10	2.25973458186e-12	-0.996633914352
2.5689638932e-10	3.94763844017e-12	-0.996633921329
2.615625195e-10	4.07063707261e-12	-0.996633920882
2.66228649679e-10	2.06234026719e-12	-0.996633918709
2.70894779858e-10	-1.6715867424e-12	-0.996633911313
2.75560910038e-10	-5.67011788359e-12	-0.996633918436
2.80227040217e-10	-7.88217848348e-12	-0.996633930115
2.84893170397e-10	-6.5935163258e-12	-0.996633908129
2.89559300576e-10	-1.44887496834e-12	-0.996633999856
2.94225430755e-10	5.95759145747e-12	-0.996633931963
2.98891560935e-10	1.23694536051e-11	-0.996633922638
3.03557691114e-10	1.41297973709e-11	-0.996633919268
3.08223821294e-10	9.01362868119e-12	-0.996633919384
3.12889951473e-10	-2.19475221285e-12	-0.99663388903
3.17556081652e-10	-1.52951760745e-11	-0.99663392228
3.22222211832e-10	-2.39700739852e-11	-0.996633924722
3.26888342011e-10	-2.25497264097e-11	-0.996633916902
3.3155447219e-10	-9.1579819106e-12	-0.996633924871
3.3622060237e-10	1.23326702967e-11	-0.996633904659
3.40886732549e-10	3.28740181305e-11	-0.996633925206
3.45552862729e-10	4.1672414178e-11	-0.996633918249
3.50218992908e-10	3.13724677525e-11	-0.996633923857
3.54885123087e-10	2.69489648512e-12	-0.996634029116
3.59551253267e-10	-3.40315457678e-11	-0.996633924361
3.64217383446e-10	-6.19705770626e-11	-0.996633916981
3.68883513625e-10	-6.4958378226e-11	-0.996633923086
3.73549643805e-10	-3.59490063391e-11	-0.996633922807
3.78215773984e-10	1.73762902607e-11	-0.996633904337
3.82881904164e-10	7.33560069114e-11	-0.996633916151
3.87548034343e-10	1.04423437256e-10	-0.99663391976
3.92214164522e-10	8.98870662286e-11	-0.99663391447
3.96880294702e-10	2.78176419094e-11	-0.996633962367
4.01546424881e-10	-6.0230911081e-11	-0.996633937975
4.0621255506e-10	-1.35496826262e-10	-0.996633920498
4.1087868524e-10	-1.58212969878e-10	-0.996633925863
4.15544815419e-10	-1.07376486875e-10	-0.996633914165
4.20210945599e-10	5.2856202661e-12	-0.996633626408
4.24877075778e-10	1.35283966401e-10	-0.996633916726
4.29543205957e-10	2.21766536485e-10	-0.996633921101
4.34209336137e-10	2.14948873683e-10	-0.996633918433
4.38875466316e-10	1.02663279501e-10	-0.996633918546
4.43541596496e-10	-7.74370890534e-11	-0.996633937223
4.48207726675e-10	-2.48462430481e-10	-0.996633921773
4.52873856854e-10	-3.25993109762e-10	-0.996633919894
4.57539987034e-10	-2.58397596894e-10	-0.996633917424
4.62206117213e-10	-5.70173349185e-11	-0.996633921965
4.66872247392e-10	2.00225211444e-10	-0.996633928572
4.71538377572e-10	3.97422452385e-10	-0.996633927519
4.76204507751e-10	4.31847911072e-10	-0.996633914279
4.80870637931e-10	2.65603239117e-10	-0.996633930412
4.8553676811e-10	-4.75943599878e-11	-0.99663394181
4.90202898289e-10	-3.76792623472e-10	-0.996633920696
4.94869028469e-10	-5.67465576703e-10	-0.99663392204
4.99535158648e-10	-5.13065583475e-10	-0.996633920267
5.04201288827e-10	-2.11663450637e-10	-0.996633927758
5.08867419007e-10	2.21430079001e-10	-0.996633919582
5.13533549186e-10	5.96162433005e-10	-0.996633916277
5.18199679366e-10	7.30535120818e-10	-0.996633922861
5.22865809545e-10	5.38001239323e-10	-0.996633922506
5.27531939724e-10	7.77816212637e-11	-0.996633980043
5.32198069904e-10	-4.59625061801e-10	-0.996633932084
5.36864200083e-10	-8.30703739204e-10	-0.996633929582
5.41530330263e-10	-8.49194863465e-10	-0.996633921912
5.46196460442e-10	-4.78424794407e-10	-0.996633917398
5.50862590621e-10	1.39716930578e-10	-0.996633873026
5.55528720801e-10	7.37862324333e-10	-0.996633927168
5.6019485098e-10	1.03917770459e-09	-0.996633923333
5.64860981159e-10	8.85839025071e-10	-0.996633920538
5.69527111339e-10	3.20128223029e-10	-0.996633898648
5.74193241518e-10	-4.23065379219e-10	-0.996633948065
5.78859371698e-10	-1.01410284667e-09	-0.996633920853
5.83525501877e-10	-1.17596598946e-09	-0.996633919796
5.88191632056e-10	-8.14731245425e-10	-0.996633929524
5.92857762236e-10	-7.13393736698e-11	-0.996634013633
5.97523892415e-10	7.33081964178e-10	-0.996633925422
6.02190022594e-10	1.23737755415e-09	-0.996633921627
6.06856152774e-10	1.20421377862e-09	-0.996633921334
6.11522282953e-10	6.32501933985e-10	-0.996633920325
6.16188413133e-10	-2.35246516209e-10	-0.996633935951
6.20854543312e-10	-1.01700569777e-09	-0.996633929763
6.25520673491e-10	-1.36157445838e-09	-0.996633923377
6.30186803671e-10	-1.10826280801e-09	-0.996633929642
6.3485293385e-10	-3.62446337741e-10	-0.996633935432
6.3951906403e-10	5.48844434032e-10	-0.996633913646
6.44185194209e-10	1.22234506601e-09	-0.996633917166
6.48851324388e-10	1.35943074316e-09	-0.996633913922
6.53517454568e-10	9.00238809106e-10	-0.996633911264
6.58183584747e-10	5.00355072148e-11	-0.996633835366
6.62849714926e-10	-8.13884328574e-10	-0.996633920861
6.67515845106e-10	-1.31194004198e-09	-0.996633917009
6.72181975285e-10	-1.23125575552e-09	-0.996633920122
6.76848105465e-10	-6.17689508974e-10	-0.996633913715
6.81514235644e-10	2.49322236589e-10	-0.996633933831
6.86180365823e-10	9.8557803091e-10	-0.996633913973
6.90846496003e-10	1.27449493257e-09	-0.996633913723
6.95512626182e-10	1.00477647421e-09	-0.996633927831
7.00178756361e-10	3.12847205899e-10	-0.99663392957
7.04844886541e-10	-4.8580759965e-10	-0.9966339387
7.0951101672e-10	-1.04189034587e-09	-0.996633915594
7.141771469e-10	-1.12660901214e-09	-0.996633922627
7.18843277079e-10	-7.26221231906e-10	-0.996633909787
7.23509407258e-10	-3.76367314647e-11	-0.996633897143
7.28175537438e-10	6.28182387659e-10	-0.996633910587
7.32841667617e-10	9.87630969583e-10	-0.996633922948
7.37507797796e-10	9.05922063844e-10	-0.996633920613
7.42173927976e-10	4.46347107936e-10	-0.996633924736
7.46840058155e-10	-1.69866382745e-10	-0.996633926303
7.51506188335e-10	-6.69738577934e-10	-0.996633920593
7.56172318514e-10	-8.49835205779e-10	-0.996633918646
7.60838448693e-10	-6.58625797719e-10	-0.99663392409
7.65504578873e-10	-2.06873377776e-10	-0.99663390172
7.70170709052e-10	2.92912238921e-10	-0.996633907835
7.74836839232e-10	6.25944629072e-10	-0.996633916085
7.79502969411e-10	6.67143268958e-10	-0.996633931726
7.8416909959e-10	4.2643003896e-10	-0.996633924998
7.8883522977e-10	3.19381821319e-11	-0.996633673371
7.93501359949e-10	-3.35851615624e-10	-0.996633932489
7.98167490128e-10	-5.25941438093e-10	-0.996633926192
8.02833620308e-10	-4.7780929433e-10	-0.996633932786
8.07499750487e-10	-2.37476394241e-10	-0.996633938243
8.12165880667e-10	7.35160219883e-11	-0.996633852152
8.16832010846e-10	3.17831495482e-10	-0.996633884298
8.21498141025e-10	4.02015262972e-10	-0.996633907349
8.26164271205e-10	3.106376634e-10	-0.996633913119
8.30830401384e-10	1.03341264414e-10	-0.996633824882
8.35496531563e-10	-1.19486160174e-10	-0.996633991321
8.40162661743e-10	-2.63930927018e-10	-0.996633931996
8.44828791922e-10	-2.80991631113e-10	-0.996633928228
8.49494922102e-10	-1.81064450739e-10	-0.996633937201
8.54161052281e-10	-2.15248732742e-11	-0.996634195722
8.5882718246e-10	1.23702382682e-10	-0.996633844612
8.6349331264e-10	1.97239299056e-10	-0.996633869311
8.68159442819e-10	1.79681177464e-10	-0.996633894817
8.72825572999e-10	9.20236028847e-11	-0.996633915062
8.77491703178e-10	-1.91380681066e-11	-0.996634125158
8.82157833357e-10	-1.04823721166e-10	-0.996633898355
8.86823963537e-10	-1.34275528807e-10	-0.996633901065
8.91490093716e-10	-1.04733235485e-10	-0.996633913959
8.96156223895e-10	-3.80115242407e-11	-0.996633873745
9.00822354075e-10	3.2550362346e-11	-0.996633870745
9.05488484254e-10	7.77346194412e-11	-0.996633901674
9.10154614434e-10	8.37297595308e-11	-0.996633943576
9.14820744613e-10	5.51044053932e-11	-0.99663398073
9.19486874792e-10	9.67546135411e-12	-0.996633586181
9.24153004972e-10	-3.11664453569e-11	-0.996634047996
9.28819135151e-10	-5.18495667465e-11	-0.996633903535
9.3348526533e-10	-4.78913897654e-11	-0.996633875653
9.3815139551e-10	-2.56308218097e-11	-0.996633839599
9.42817525689e-10	2.42705843298e-12	-0.99663383911
9.47483655869e-10	2.38951421953e-11	-0.996633950564
9.52149786048e-10	3.15120009597e-11	-0.996633956835
9.56815916227e-10	2.50615440698e-11	-0.996634019646
9.61482046407e-10	1.00300564931e-11	-0.996633492737
9.66148176586e-10	-5.78848557148e-12	-0.996634548833
9.70814306766e-10	-1.5925573503e-11	-0.996633858836
9.75480436945e-10	-1.75709310372e-11	-0.996633915678
9.80146567124e-10	-1.19228530764e-11	-0.996633793632
9.84812697304e-10	-2.83555876891e-12	-0.996633952007
9.89478827483e-10	5.31641595913e-12	-0.996633629413
9.94144957662e-10	9.51385450205e-12	-0.996633176774
9.98811087842e-10	9.00100335642e-12	-0.996633653789
1.00347721802e-09	5.07316104914e-12	-0.996633710316
1.0081433482e-09	8.39596487617e-14	-0.996544204716
1.01280947838e-09	-3.74456293505e-12	-0.996633618383
1.01747560856e-09	-5.18055259745e-12	-0.996633175467
1.02214173874e-09	-4.23837696868e-12	-0.996634628596
1.02680786892e-09	-1.87212495873e-12	-0.996637714576
1.0314739991e-09	6.34374817699e-13	-0.996628084215
1.03614012928e-09	2.26094968203e-12	-0.996631989103
1.04080625946e-09	2.59167993123e-12	-0.996631602258
1.04547238964e-09	1.8281757616e-12	-0.99663295383
1.05013851981e-09	5.52156768194e-13	-0.996630691027
1.05480464999e-09	-6.03097218936e-13	-0.99664268435
1.05947078017e-09	-1.21745065578e-12	-0.996633009185
1.06413691035e-09	-1.1945049204e-12	-0.996633879145
1.06880304053e-09	-7.13891633813e-13	-0.996638801241
1.07346917071e-09	-8.6633131462e-14	-0.996671760591
1.07813530089e-09	4.02962250493e-13	-0.996630098785
1.08280143107e-09	6.0185615583e-13	-0.996632926267
1.08746756125e-09	5.10835782958e-13	-0.99663569435
1.09213369143e-09	2.41614003748e-13	-0.99663929374
1.09679982161e-09	-3.71538236616e-14	-0.996527908643
1.10146595179e-09	-1.97984634891e-13	-0.996611469762
1.10613208197e-09	-2.4601730397e-13	-0.996615333883
1.11079821215e-09	-1.99931558341e-13	-0.996631162758
1.11546434233e-09	-1.09082768098e-13	-0.996636537465
1.12013047251e-09	-1.00138211876e-14	-0.996261777664
1.12479660269e-09	6.80114156225e-14	-0.996641723213
1.12946273286e-09	1.06897519712e-13	-0.996637589208
1.13412886304e-09	1.06899736569e-13	-0.996609451327
1.13879499322e-09	7.53305767695e-14	-0.996590969039
1.1434611234e-09	2.8684516946e-14	-0.996533974256
1.14812725358e-09	-1.82566818369e-14	-0.99653276949
1.15279338376e-09	-5.10792708717e-14	-0.996675751217
1.15745951394e-09	-6.32984488478e-14	-0.9966982622
1.16212564412e-09	-5.52852409086e-14	-0.996645496756
1.1667917743e-09	-3.28858489767e-14	-0.996633356219
1.17145790448e-09	-5.17927487415e-15	-0.994271571561
1.17612403466e-09	1.93008404893e-14	-0.9964644947
1.18079016484e-09	3.44245097224e-14	-0.996556405466
1.18545629502e-09	3.79225277456e-14	-0.996592376928
1.1901224252e-09	3.12795212889e-14	-0.99663748264
1.19478855538e-09	1.8328098048e-14	-0.996661972518
1.19945468556e-09	3.69908106461e-15	-0.992182033499
1.20412081573e-09	-8.88938995925e-15	-0.996066914401
1.20878694591e-09	-1.72421874572e-14	-0.996371386965
1.21345307609e-09	-2.09252621291e-14	-0.996561710963
1.21811920627e-09	-2.04869831087e-14	-0.99675657743
1.22278533645e-09	-1.68948877344e-14	-0.99663216959
1.22745146663e-09	-1.12221263677e-14	-0.996419828382
1.23211759681e-09	-4.2639301392e-15	-0.993971749906
1.23678372699e-09	3.22843709079e-15	-0.991032987363
1.24144985717e-09	1.03196177986e-14	-0.995712393987
1.24611598735e-09	1.58522178731e-14	-0.996086862128
1.25078211753e-09	1.86764190437e-14	-0.996420759163
1.25544824771e-09	1.78855533005e-14	-0.996555878162
1.26011437789e-09	1.32509172087e-14	-0.996066235476
1.26478050807e-09	5.57548935269e-15	-0.994676581665
1.26944663825e-09	-3.45153035349e-15	-0.990360445977
1.27411276843e-09	-1.1767451232e-14	-0.996215955237
1.2787788986e-09	-1.73995294545e-14	-0.996612867229
1.28344502878e-09	-1.89678595131e-14	-0.996554396916
1.28811115896e-09	-1.61951337026e-14	-0.996629464121
1.29277728914e-09	-9.9244486092e-15	-0.996411962102
1.29744341932e-09	-1.76639947351e-15	-0.971548431523
1.3021095495e-09	6.30781477465e-15	-0.994596802208
1.30677567968e-09	1.2468499806e-14	-0.995915042997
1.31144180986e-09	1.55501827931e-14	-0.996190952272
1.31610794004e-09	1.52062435312e-14	-0.996192212576
1.32077407022e-09	1.17864725818e-14	-0.99580494065
1.3254402004e-09	6.22651823246e-15	-0.994229740561
1.33010633058e-09	-1.88991632127e-16	-0.38828308322
1.33477246076e-09	-6.21206411923e-15	-0.995911989877
1.33943859094e-09	-1.08529829079e-14	-0.996844288233
1.34410472112e-09	-1.34503310509e-14	-0.996497506442
1.3487708513e-09	-1.37300760648e-14	-0.996697512548
1.35343698147e-09	-1.1807739186e-14	-0.996605534681
1.35810311165e-09	-8.09974835624e-15	-0.996231692575
1.36276924183e-09	-3.25752583623e-15	-0.993742892274
1.36743537201e-09	1.91231299218e-15	-0.977435082578
1.37210150219e-09	6.60341270094e-15	-0.994876794742
1.37676763237e-09	1.01223238521e-14	-0.995644039956
1.38143376255e-09	1.199963788e-14	-0.996080259106
1.38609989273e-09	1.20241188676e-14	-0.996434597469
1.39076602291e-09	1.02846454773e-14	-0.995888445813
1.39543215309e-09	7.20251022182e-15	-0.995209810887
1.40009828327e-09	3.43234529628e-15	-0.992466898304
1.40476441345e-09	-3.13942562147e-16	-0.635654485138
1.40943054363e-09	-3.34653462629e-15	-0.992016155373
1.41409667381e-09	-5.12141809178e-15	-0.99410918861
1.41876280399e-09	-5.28883107881e-15	-0.994186010306
1.42342893417e-09	-3.9362907965e-15	-0.993226912709
1.42809506434e-09	-1.19381014373e-15	-0.958892632826
1.43276119452e-09	2.19154885539e-15	-0.98764849945
1.4374273247e-09	5.80243438554e-15	-0.994051241577
1.44209345488e-09	8.62954899689e-15	-0.996000514564
1.44675958506e-09	1.04833923814e-14	-0.99621369628
1.45142571524e-09	1.06918452777e-14	-0.99585977719
1.45609184542e-09	9.37879201392e-15	-0.995347119612
1.4607579756e-09	6.74961054874e-15	-0.99539245851
1.46542410578e-09	3.1974366299e-15	-0.991249172582
1.47009023596e-09	-3.28769292718e-16	-0.648576063696
1.47475636614e-09	-3.60127557307e-15	-0.992726370617
1.47942249632e-09	-5.73151037151e-15	-0.994549602541
1.4840886265e-09	-6.4902700115e-15	-0.995701252997
1.48875475668e-09	-5.84470331318e-15	-0.994239379204
1.49342088686e-09	-3.95333264416e-15	-0.99221990182
1.49808701704e-09	-1.18092829466e-15	-0.97122834183
1.50275314721e-09	1.919879904e-15	-0.978755670788
1.50741927739e-09	4.75466415526e-15	-0.994138536389
1.51208540757e-09	6.95732775472e-15	-0.995500823644
1.51675153775e-09	8.17485594688e-15	-0.995603463898
1.52141766793e-09	8.24087198492e-15	-0.995529627672
1.52608379811e-09	7.21402285608e-15	-0.995084799266
1.53074992829e-09	5.27169760592e-15	-0.994987903172
1.53541605847e-09	2.7546362944e-15	-0.986923017452
1.54008218865e-09	9.06345339848e-17	-0.122170401003
1.54474831883e-09	-2.27183964083e-15	-0.989093136298
1.54941444901e-09	-3.92460427439e-15	-0.993440727186
1.55408057919e-09	-4.52121805432e-15	-0.9943171604
1.55874670937e-09	-3.89614833419e-15	-0.99297204381
1.56341283955e-09	-2.1660947035e-15	-0.985137152325
1.56807896973e-09	3.34414007485e-16	-0.648327255739
1.57274509991e-09	3.12868545826e-15	-0.990390880885
1.57741123008e-09	5.6924758863e-15	-0.994732342685
1.58207736026e-09	7.5436519615e-15	-0.995528793965
1.58674349044e-09	8.34160282949e-15	-0.995431279449
1.59140962062e-09	7.97742871206e-15	-0.99580299409
1.5960757508e-09	6.58479715677e-15	-0.995500212551
1.60074188098e-09	4.45723394314e-15	-0.993093805782
1.60540801116e-09	1.96221720287e-15	-0.986077997031
1.61007414134e-09	-4.9721344386e-16	-0.801288916253
1.61474027152e-09	-2.55318812901e-15	-0.990872180431
1.6194064017e-09	-3.93801114101e-15	-0.992577330238
1.62407253188e-09	-4.47880648631e-15	-0.993784804594
1.62873866206e-09	-4.11738018803e-15	-0.992989284274
1.63340479224e-09	-2.97944345732e-15	-0.991103271908
1.63807092242e-09	-1.309222983e-15	-0.958832399492
1.6427370526e-09	5.97217570538e-16	-0.870442356878
1.64740318278e-09	2.3615172666e-15	-0.986435554971
1.65206931296e-09	3.58137170558e-15	-0.991985561326
1.65673544313e-09	4.0111909402e-15	-0.99361948028
1.66140157331e-09	3.57124748552e-15	-0.99144404245
1.66606770349e-09	2.30147760369e-15	-0.989785254335
1.67073383367e-09	4.220959954e-16	-0.741394097223
1.67539996385e-09	-1.70222247108e-15	-0.981642516166
1.68006609403e-09	-3.71644265677e-15	-0.992669275413
1.68473222421e-09	-5.28756380898e-15	-0.994741304216
1.68939835439e-09	-6.11224878319e-15	-0.99550153305
1.69406448457e-09	-6.06303355402e-15	-0.995272672308
1.69873061475e-09	-5.20672977015e-15	-0.994519635776
1.70339674493e-09	-3.68489929084e-15	-0.993352306621
1.70806287511e-09	-1.72355546142e-15	-0.978854060409
1.71272900529e-09	3.37275138582e-16	-0.691397176399
1.71739513547e-09	2.18332795579e-15	-0.982848536163
1.72206126565e-09	3.58986057857e-15	-0.991778790785
1.72672739583e-09	4.38696609719e-15	-0.993579700651
1.731393526e-09	4.51402210384e-15	-0.993301924286
1.73605965618e-09	4.0386310941e-15	-0.991535638327
1.74072578636e-09	3.08521117249e-15	-0.988980060245
1.74539191654e-09	1.80552442596e-15	-0.983385107787
1.75005804672e-09	4.19114110275e-16	-0.756171575165
1.7547241769e-09	-8.47476657848e-16	-0.934270093447
1.75939030708e-09	-1.83288728429e-15	-0.980268332552
1.76405643726e-09	-2.39230078327e-15	-0.988479452423
1.76872256744e-09	-2.45854013768e-15	-0.987796561689
1.77338869762e-09	-2.00292358343e-15	-0.981038237679
1.7780548278e-09	-1.12198350924e-15	-0.967992345236
1.78272095798e-09	4.10256738034e-17	-0.0226044399082
1.78738708816e-09	1.23311884718e-15	-0.969613152816
1.79205321834e-09	2.22184257631e-15	-0.984680257883
1.79671934852e-09	2.79967213455e-15	-0.991081149124
1.8013854787e-09	2.78633746403e-15	-0.988480044672
1.80605160887e-09	2.17511308494e-15	-0.988253953464
1.81071773905e-09	1.02113959645e-15	-0.946226459718
1.81538386923e-09	-4.58451239989e-16	-0.804866518557
1.82004999941e-09	-2.00083562024e-15	-0.983960485079
1.82471612959e-09	-3.2858993967e-15	-0.992618740677
1.82938225977e-09	-4.0824714364e-15	-0.992927656436
1.83404838995e-09	-4.27837651178e-15	-0.993908790135
1.83871452013e-09	-3.79400684733e-15	-0.99287391232
	9.39363631165e-14	0.996599289969
```

**Comment by thliebig** [comment]
I think the problem is that you re-used the same port number. Ideally this should be allowed, but currently this seems to be broken. Just avoid this, this is usually not what you want...
